## creating nd array from scratch

In [7]:
import numpy as np

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2  


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2  

    
])

# arr=np.zeros((6,3),dtype=np.int16)
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

# arr=np.zeros_like(arr3)
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr=arr=np.ones((6,3),dtype=np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int16
(6, 3)
2
18


## arrray creation with random numbers

In [14]:
arr=np.random.rand(2,3)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[0.56855009 0.01994695 0.98383297]
 [0.2034045  0.07158944 0.72080766]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


In [18]:
arr=np.random.randint(1,10,(2,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[8 2 9]
 [1 2 9]]
<class 'numpy.ndarray'>
int32
(2, 3)
2
6


In [19]:
arr=np.random.uniform(1,10,(2,3))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[6.0908712  3.9488054  4.38973219]
 [4.11455938 4.34811178 7.47938606]]
<class 'numpy.ndarray'>
float64
(2, 3)
2
6


## array creation with range functions

In [21]:
arr=np.arange(1,10,1)

print(arr)

[1 2 3 4 5 6 7 8 9]


In [23]:
arr=np.linspace(1,5,6)
print(arr)

[1.  1.8 2.6 3.4 4.2 5. ]
