## creating nd array from scratch

In [7]:
import numpy as np

arr3 = np.array([
    #1st floor
    [ [1,2,3], # row1
      [4,5,6]  ], #row2 

    #2nd floor

     [[1,2,3], # row1
      [4,5,6]  ], #row2  


    #3rd floor
      [[1,2,3], # row1
      [4,5,6]  ] #row2  

    
])

# arr=np.zeros((6,3),dtype=np.int16)
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)

# arr=np.zeros_like(arr3)
# print(arr)
# print(type(arr))
# print(arr.dtype)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)


arr=arr=np.ones((6,3),dtype=np.int16)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr.size)

[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
<class 'numpy.ndarray'>
int16
(6, 3)
2
18
