In [4]:
import numpy as np
arr=np.random.randint(1,100,size=(10,5))
print(arr)
print(arr.shape)

[[30 67 80 30 38]
 [85 81 90 16 99]
 [ 3 95 35 91 17]
 [87 76 97 84 92]
 [61 32 17 52 58]
 [16  9 53 46 76]
 [12  2 30 56 90]
 [95 61 22 74 33]
 [58 50 99 22  9]
 [82 38 96 21  7]]
(10, 5)


In [ ]:
b=arr.reshape(5,10)
print(b.shape)
print(b)
print(b.ndim)

[[30 67 80 30 38 85 81 90 16 99]
 [ 3 95 35 91 17 87 76 97 84 92]
 [61 32 17 52 58 16  9 53 46 76]
 [12  2 30 56 90 95 61 22 74 33]
 [58 50 99 22  9 82 38 96 21  7]]
2


In [ ]:
flatten=b.flatten()
print(flatten.ndim)


generilized_flattening=np.ravel(b,order="C") #or "F"
print(generilized_flattening)

1
[30 67 80 30 38 85 81 90 16 99  3 95 35 91 17 87 76 97 84 92 61 32 17 52
 58 16  9 53 46 76 12  2 30 56 90 95 61 22 74 33 58 50 99 22  9 82 38 96
 21  7]


In [13]:
mat=np.array([[10,20,30],[30,40,50]])
print(mat)
transpose=mat.T
print(transpose)

[[10 20 30]
 [30 40 50]]
[[10 30]
 [20 40]
 [30 50]]


## arithmatic operations 

In [14]:
x=np.array([10,20,30,40])
y=np.array([[2,3,4,5]])

add=x+y
print(add)

[[12 23 34 45]]
