In [1]:
import numpy as np
arr=np.random.randint(1,100,size=(5,10))
print(arr)

[[63 23 43 32 62  4 80 50 62 61]
 [26 36 94 23 36 57 99 89 68  4]
 [95  9 38 42 96 29 40  3  7 50]
 [96 58 65  9 45 85 37 20 25 14]
 [81 92 55 34 78  9 65 51 22 50]]
