### 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.

In [3]:
import numpy as np
array1d=np.array([1,2,3,4,5])
print("1D Array:",array1d)
array2d=np.array([[1,2,3],[4,5,6]])
print("2D Array:",array2d)
array3d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("3D Array:",array3d)

1D Array: [1 2 3 4 5]
2D Array: [[1 2 3]
 [4 5 6]]
3D Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]


## 1 . Create a 1D, 2D, and 3D NumPy array and print their dimensions and shapes.
<p>an array of zeros of shape (3,3)</p>
<p>an array of ones of shape (2,5)</p>
<p>n array filled with 7</p>

In [10]:
#1

# 1️⃣ Array of zeros with shape (3,3)
arr1=np.zeros((3,3),dtype=np.int8)

print(arr1)
# 2️⃣ Array of ones with shape (2,5)
arr1=np.ones((2,5),dtype=np.int8)

print(arr1)
# 3️⃣ Array filled with 7

sevens_arr=np.full((3,3),7)
print(sevens_arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


In [13]:
even_Numbers=np.arange(10,51,2)
print(even_Numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [14]:
matrix=np.arange(16).reshape(4,4)
print("Original 4*4 Matrix \n",matrix)

first_row=matrix[0:2:1,1:3:1]

print("Printing test")
print(first_row)
row_0=matrix[0:1,]
print("First row\n",row_0)
# row_1=matrix[1:2,]
# print("Row 1\n",row_1)
last_column=matrix[::, -1::]
print("Last Column\n",last_column)

sub_array=matrix[1:3,1:3]
print("Sub array\n",sub_array)

Original 4*4 Matrix 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Printing test
[[1 2]
 [5 6]]
First row
 [[0 1 2 3]]
Last Column
 [[ 3]
 [ 7]
 [11]
 [15]]
Sub array
 [[ 5  6]
 [ 9 10]]


### 5 . Add a 1D array [1,2,3] to each row of a 3×3 matrix.

In [16]:
matrix=np.array([[4,5,6],[7,8,9],[10,11,12]])
print("Input",matrix)
tobeAdded=np.array([1,2,3])

result=matrix+tobeAdded
print("result\n",result)

Input [[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
result
 [[ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


### Given two arrays A and B, compute:
(A + B) / 2


A**2 + B**2


In [17]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
B=np.array([[9,8,7],[6,5,4],[3,2,1]])
print(B)
result1=(A+B)/2
result2=A**2+B**2
print("Result1\n",result1)
print("Result2\n",result2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]
Result1
 [[5. 5. 5.]
 [5. 5. 5.]
 [5. 5. 5.]]
Result2
 [[82 68 58]
 [52 50 52]
 [58 68 82]]
